/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
 */

public class Find {

    public static char findTheDifference(String s, String t) {
        char[] arr1 = s.toCharArray();
        char[] arr2 = t.toCharArray();

        int tmp_i = 0,tmp_j = 0, h = 0;
        while (true){
            for (int i = 0; i < arr2.length; i++) {
                if(arr2[h] == arr2[i]){
                    tmp_i += 1;
                }
            }
            for (int j = 0; j < arr1.length; j++){
                if(arr2[h] == arr1[j]){
                    tmp_j += 1;
                }
            }

            if(tmp_i != tmp_j){
                return arr2[h];
            }else {
                tmp_i = 0;
                tmp_j = 0;
                h++;
            }
        }
    }

    public static void main(String[] args){
        System.out.println(findTheDifference("ymbgaraibkfmvocpiz" +
                "dydugvalagaivdbfsfbepeyccqfepzvtpyxtbadkhmwmosw" +
                "rcxnargtlswqemafandgkmydtimuzvjwxvlfwlhvkrgcsith" +
                "aqlcvrihrwqkpjdhgfgreqoxzfvhjzojhghfwbvpfzectwwh" +
                "exthbsndovxejsntmjihchaotbgcysfdaojkjldprwyrnis" +
                "chrgmtvjcorypvopfmegizfkvudubnejzfqffvgdoxohuin" +
                "kyygbdzmshvyqyhsozwvlhevfepdvafgkqpkmcsikfyxczco" +
                "vrmwqxxbnhfzcjjcpgzjjfateajnnvlbwhyppdleahgaypxi" +
                "dkpwmfqwqyofwdqgxhjaxvyrzupfwesmxbjszolgwqvfiozof" +
                "ncbohduqgiswuiyddmwlwubetyaummenkdfptjczxemryuotrr" +
                "ymrfdxtrebpbjtpnuhsbnovhectpjhfhahbqrfbyxggobsweefcwxpq" +
                "sspyssrmdhuelkkvyjxswjwofngpwfxvknkjviiavorwyfzlnktmfwxk" +
                "vwkrwdcxjfzikdyswsuxegmhtnxjraqrdchaauazfhtklxsksbhwgjphgbasfnlwqwukprgvihntsyymdrfovaszjywuqygpvjtvlsvvqbvzsmgweiayhlubnbsitvfxawhfmfiatxvqrcwjshvovxknnxnyyfexqycrlyksderlqarqhkxyaqwlwoqcribumrqjtelhwdvaiysgjlvksrfvjlcaiwrirtkkxbwgicyhvakxgdjwnwmubkiazdjkfmotglclqndqjxethoutvjchjbkoasnnfbgrnycucfpeovruguzumgmgddqwjgdvaujhyqsqtoexmnfuluaqbxoofvotvfoiexbnprrxptchmlctzgqtkivsilwgwgvpidpvasurraqfkcmxhdapjrlrnkbklwkrvoaziznlpor","qhxepbshlrhoecdaodgpousbzfcqjxulatciapuftffahhlmxbufgjuxstfjvljybfxnenlacmjqoymvamphpxnolwijwcecgwbcjhgdybfffwoygikvoecdggplfohemfypxfsvdrseyhmvkoovxhdvoavsqqbrsqrkqhbtmgwaurgisloqjixfwfvwtszcxwktkwesaxsmhsvlitegrlzkvfqoiiwxbzskzoewbkxtphapavbyvhzvgrrfriddnsrftfowhdanvhjvurhljmpxvpddxmzfgwwpkjrfgqptrmumoemhfpojnxzwlrxkcafvbhlwrapubhveattfifsmiounhqusvhywnxhwrgamgnesxmzliyzisqrwvkiyderyotxhwspqrrkeczjysfujvovsfcfouykcqyjoobfdgnlswfzjmyucaxuaslzwfnetekymrwbvponiaojdqnbmboldvvitamntwnyaeppjaohwkrisrlrgwcjqqgxeqerjrbapfzurcwxhcwzugcgnirkkrxdthtbmdqgvqxilllrsbwjhwqszrjtzyetwubdrlyakzxcveufvhqugyawvkivwonvmrgnchkzdysngqdibhkyboyftxcvvjoggecjsajbuqkjjxfvynrjsnvtfvgpgveycxidhhfauvjovmnbqgoxsafknluyimkczykwdgvqwlvvgdmufxdypwnajkncoynqticfetcdafvtqszuwfmrdggifokwmkgzuxnhncmnsstffqpqbplypapctctfhqpihavligbrutxmmygiyaklqtakdidvnvrjfteazeqmbgklrgrorudayokxptswwkcircwuhcavhdparjfkjypkyxhbgwxbkvpvrtzjaetahmxevmkhdfyidhrdeejapfbafwmdqjqszwnwzgclitdhlnkaiyldwkwwzvhyorgbysyjbxsspnjdewjxbhpsvj"));
    }
}
